// SPDX-License-Identifier: MIT
//
// ProcessFork — TypeScript SDK.
//
// Wraps the napi-rs cdylib. The cdylib's TypeScript types live in
// `index.d.ts` (auto-generated by `napi build`); this file adds a thin
// ergonomic layer (Manifest typed object, JSON parsing of readManifest).

import {
  PfStore as _PfStore,
  digestOf,
  snapshotFilesystem,
  checkoutFilesystem,
  readManifest as _readManifestRaw,
  merge as _merge,
  type Message,
  type MergeOpts,
  type MergeReport,
  type WorldConflict,
} from "../index.js";

export {
  digestOf,
  snapshotFilesystem,
  checkoutFilesystem,
  _merge as merge,
  type Message,
  type MergeOpts,
  type MergeReport,
  type WorldConflict,
};

/**
 * Local content-addressed `.pfimg` store. Re-exported from the cdylib;
 * we attach `readManifest` as an instance method here so callers don't
 * have to JSON.parse themselves.
 */
export class PfStore {
  private inner: _PfStore;

  private constructor(inner: _PfStore) {
    this.inner = inner;
  }

  /** Open (or create) a store rooted at `path`. `~` is expanded. */
  static open(path: string): PfStore {
    return new PfStore(_PfStore.open(path));
  }

  /** Total compressed bytes on disk. */
  physicalBytes(): number {
    return this.inner.physicalBytes();
  }

  /** Underlying napi handle (for use with the free functions). */
  get _raw(): _PfStore {
    return this.inner;
  }
}

/**
 * Convenience wrapper around the napi `readManifest` (which returns the
 * canonical-JSON string). Returns the parsed manifest object.
 */
export function readManifest(store: PfStore, cid: string): Manifest {
  return JSON.parse(_readManifestRaw(store._raw, cid)) as Manifest;
}

// --------------------------- Manifest types ---------------------------

export interface Manifest {
  schemaVersion: number;
  mediaType: string;
  agent: { kind: string; version: string; fingerprint: string };
  model: { base: string; diff: string };
  cache: { layout: string; manifest: string };
  world: { fs: string; env: string; procs: string };
  effects: { ledger: string };
  trace: { messages: string };
  createdAt: string;
  parents: string[];
}
