/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** `digestOf(bytes: Buffer): string` — SHA-256 of bytes, OCI-style. */
export declare function digestOf(bytes: Array<number>): string
/** Plain old JS object for one chat message. */
export interface Message {
  role: string
  content: string
}
/** `snapshotFilesystem(store, agentKind, fsRoot, env, messages): string` */
export declare function snapshotFilesystem(store: PfStore, agentKind: string, fsRoot: string, env: Record<string, string>, messages: Array<Message>): string
/**
 * `checkoutFilesystem(store, cid, targetPath): void`. `targetPath` MUST NOT
 * already exist.
 */
export declare function checkoutFilesystem(store: PfStore, cid: string, targetPath: string): void
/**
 * `readManifest(store, cid): string` — returns the manifest JSON as a
 * string. The TS wrapper at `ts/index.ts` JSON-parses for callers that
 * want a typed object.
 */
export declare function readManifest(store: PfStore, cid: string): string
export interface WorldConflict {
  path: string
  aDigest: string
  bDigest: string
  xDigest?: string
}
export interface MergeReport {
  mergedCid: string
  ancestor: string
  overall: string
  worldConflicts: Array<WorldConflict>
  traceSummary: string
  modelAppliedTaskArithmetic: boolean
}
export interface MergeOpts {
  alpha?: number
  dareP?: number
  seed?: number
}
/** `merge(store, a, b, opts?): MergeReport` — three-way merge B into A. */
export declare function merge(store: PfStore, a: string, b: string, opts?: MergeOpts | undefined | null): MergeReport
/** JS-side handle to a `pf_core::store::PfStore`. Cheap to clone (Arc'd). */
export declare class PfStore {
  /** Open (or create) a ProcessFork store at `path`. `~` is expanded. */
  static open(path: string): PfStore
  /** Total compressed bytes on disk. */
  physicalBytes(): number
}
